package com.bpifrance.https_rest_call;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Token implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Token() {
    }




}